language: java
sudo: required
dist: trusty

services:
  - mysql

env:
  global:
    - RELEASE_VERSION="0.1.0"
    - RELEASE_PLACEHOLDER="@release.number@"
    - BUILD_PLACEHOLDER="@build.number@"

before_install:
  - sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
  - sudo apt-get update && sudo apt-get install commandbox
  - mkdir modules
  - mkdir modules/cfboom-security
  - mv apidocs/  modules/cfboom-security/
  - mv auth/  modules/cfboom-security/
  - mv authentication/  modules/cfboom-security/
  - mv core/  modules/cfboom-security/
  - mv crypto/ modules/cfboom-security/
  - mv handlers/ modules/cfboom-security/
  - mv interceptors/ modules/cfboom-security/
  - mv ldap/ modules/cfboom-security/
  - mv lib/ modules/cfboom-security/
  - mv oauth2/ modules/cfboom-security/
  - mv tests/ modules/cfboom-security/
  - mv views/ modules/cfboom-security/
  - mv web/ modules/cfboom-security/
  - mv AuthenticationExceptions.md modules/cfboom-security/
  - mv box.json modules/cfboom-security/
  - mv LICENSE modules/cfboom-security/
  - mv ModuleConfig.cfc modules/cfboom-security/
  - mv README.md modules/cfboom-security/

install:
  - box coldbox create app
  - box install coldbox
  - box install testbox
  - box install cbjavaloader
  - box install cfboom-lang
  - box install cfboom-util
  - box server start port=45123 rewritesEnable=true JVMArgs="-DcfAdminPassword=J5HIsmsWk26" openBrowser=false

before_script:
  - curl http://localhost:45123/
  - curl --data "new_password=J5HIsmsWk26&new_password_re=J5HIsmsWk26&lang=en&rememberMe=s&submit=submit" http://localhost:45123/lucee/admin/web.cfm
  - curl http://localhost:45123/modules/cfboom-security/tests/travis_db.cfm

script: > 
    testResults="echo $(box testbox run runner=http://localhost:45123/modules/cfboom-security/tests/runner.cfm)";
    echo "$testResults";
    if grep -i "\[Failures: [1-9][0-9]\?[0-9]\?\]\|\[Errors: [1-9][0-9]\?[0-9]\?\]\|<t[^>]*>\|<b[^>]*>" <<< $testResults;  then exit 1; fi

after_success:
  - sudo sed -i "s/$RELEASE_PLACEHOLDER/${RELEASE_VERSION}/g;" 'modules/cfboom-security/box.json'
  - sleep 2
  - sudo sed -i "s/$BUILD_PLACEHOLDER/${TRAVIS_BUILD_NUMBER}/g" 'modules/cfboom-security/box.json'
  - sleep 2
